### ISSUE TITLE
Removing GRE destroys packet

### ISSUE THREAD

**Issue by DigiAngel** [lpefferkorn/ipdecap#1]
Topic says it...including pcapng with the original packet and the de-gre'd packet.  Thank you.

**Comment by DigiAngel** [comment]
Github sucks and won't take a zip file..YAY.

**Comment by lpefferkorn** [comment]
Try to host it somewhere else?

**Comment by DigiAngel** [comment]
On 2016-05-19 12:45, Loic Pefferkorn wrote:

> Try to host it somewhere else?
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub [1]
> 
>   *
> 
> ## Links:
> 
> [1] 
> https://github.com/lpefferkorn/ipdecap/issues/1#issuecomment-220415481

Maybe emailing as attachment will make it through.

**Comment by DigiAngel** [comment]
![gre-mreged-test](https://cloud.githubusercontent.com/assets/947191/15405702/3403c452-1dc0-11e6-86c4-d57468954428.jpg)

Ok this is dumb but I renamed this from .zip to .jpg and it looks to be here.  Thanks for looking into this!

**Comment by lpefferkorn** [comment]
Expect some delay, as I move to a new country

**Comment by DigiAngel** [comment]
Wow congrats and hope it's a good move.

**Comment by lpefferkorn** [comment]
Hello,

I know this occurred a long time ago, but it appears that the pcap file is somehow corrupted:
```
$ ./src/ipdecap -i gre-mreged.pcapng -o out_err_gre.pcap
error: Error while reading input file: an interface has a snapshot length 262144 different from the type of the first interface
```

Now this kind of errors are caught with the commit https://github.com/lpefferkorn/ipdecap/commit/398f956eda42afd58a0072b075b4efc5780c1d35

Since this seems to be an error related to the file, I am resolving the issue. Thanks for reporting!
