### ISSUE TITLE
Segmentation fault in remove_ieee8021q_header if in_payload_len malformed

### ISSUE THREAD

**Issue by aapo** [lpefferkorn/ipdecap#4]
If input pcap is malformed/corrupted ipdecap segfaults.

    diff --git a/src/ipdecap.c b/src/ipdecap.c
    index 00e6be7..42f5e78 100644
    --- a/src/ipdecap.c
    +++ b/src/ipdecap.c
    @@ -163,9 +163,12 @@ void remove_ieee8021q_header(const u_char *in_payload, const int in_payload_len,
    
    /* Skip ieee 802.1q bytes */
    payload_src += VLAN_TAG_LEN;
    -  memcpy(payload_dst, payload_src, in_payload_len
    -                                  - 2*sizeof(struct ether_addr)
    -                                  - VLAN_TAG_LEN);
    +  int how_much_to_copy = in_payload_len - 2*sizeof(struct ether_addr) - VLAN_TAG_LEN;
    +  if (how_much_to_copy < 1) {
    +      //printf("Trying memcpy with non-positive length (%d), skipping\n",how_much_to_copy);
    +      return;
    +  }
    +  memcpy(payload_dst, payload_src, how_much_to_copy);
    
    /* TODO: Should I check for minimum frame size, even if most drivers don't supply FCS (4 bytes) ? */
    out_pkthdr->len = in_payload_len - VLAN_TAG_LEN;

**Comment by lpefferkorn** [comment]
Thanks for the bug report! By any chance could you provide me a pcap file with such corrupted packet? I would then add it to the functional tests

**Comment by aapo** [comment]
[ipdecap_issue4.zip](https://github.com/lpefferkorn/ipdecap/files/2133648/ipdecap_issue4.zip)
This pcapng-file is minimal which triggers the bug.

**Comment by lpefferkorn** [comment]
Fixed in https://github.com/lpefferkorn/ipdecap/commit/e077c87c526fb3c864093c1084df5954c5893ccb thank you!
