### ISSUE TITLE
doublefree with malformed pcapng inputfile

### ISSUE THREAD

**Issue by aapo** [lpefferkorn/ipdecap#5]
pcapng for **ping -c 1 localhost** (ipv6)
With one (intentional) bitflip, attached.

    Program received signal SIGABRT, Aborted.
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
    #1  0x00007ffff736b801 in __GI_abort () at abort.c:79
    #2  0x00007ffff73b4897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff74e1b9a "%s\n")
        at ../sysdeps/posix/libc_fatal.c:181
    #3  0x00007ffff73bb90a in malloc_printerr (str=str@entry=0x7ffff74e3870 "double free or corruption (out)") at malloc.c:5350
    #4  0x00007ffff73c2e75 in _int_free (have_lock=0, p=0x555555763cb0, av=0x7ffff7716c40 <main_arena>) at malloc.c:4278
    #5  __GI___libc_free (mem=0x555555763cc0) at malloc.c:3124
    #6  0x000055555555661c in handle_packets (bpf_filter=0x0, pkthdr=0x7fffffffdbe0, bytes=0x55555575c74c "") at ipdecap.c:454
    #7  0x00007ffff773ad19 in ?? () from /usr/lib/x86_64-linux-gnu/libpcap.so.0.8
    #8  0x0000555555556a35 in main (argc=5, argv=0x7fffffffde68) at ipdecap.c:540
    
[ipdecap_issue5.zip](https://github.com/lpefferkorn/ipdecap/files/2133694/ipdecap_issue5.zip)

**Comment by lpefferkorn** [comment]
Thanks for the report, I'll have a look

**Comment by lpefferkorn** [comment]
Fixed in https://github.com/lpefferkorn/ipdecap/commit/6260b71ef6af769f1e4660c31f50822dd38f0c77
